name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  upload-release:
    runs-on: ubuntu-latest
    needs:
      - build-macos
      - build-linux
    permissions:
      contents: write

    steps:
      - id: vars
        run: |
          echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - uses: actions/download-artifact@v2
        with:
          name: gitswitcher-macos

      - uses: actions/download-artifact@v2
        with:
          name: gitswitcher-linux

      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            gitswitcher-macos
            gitswitcher-linux
          tag_name: ${{ steps.vars.outputs.tag }}
          name: Release ${{ steps.vars.outputs.tag }}
          body: Release ${{ steps.vars.outputs.tag }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}

  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v1

      - name: Install deps
        run: bun install

      - name: Builds
        run: bun run build

      - name: rename
        run: mv gitswitcher gitswitcher-macos

      - uses: actions/upload-artifact@v2
        with:
          name: gitswitcher-macos
          path: gitswitcher-macos

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v1

      - name: Install deps
        run: bun install

      - name: Builds
        run: bun run build

      - name: rename
        run: mv gitswitcher gitswitcher-linux

      - uses: actions/upload-artifact@v2
        with:
          name: gitswitcher-linux
          path: gitswitcher-linux
